### ISSUE TITLE
ACT 1.3 Missing phrase in ACT 1:3 

### ISSUE THREAD

**Issue by beniza** [unfoldingWord/ulb-en#1]
"After his suffering he presented himself alive to them by many convincing proofs, appearing to them during forty days and speaking about the kingdom of God." --NRSV89
"the ones to whom he appeared alive after his suffering. For forty days he kept appearing to them, saying things about the kingdom of God." ULB

The phrase **by many convincing proofs** is missing in ULB

**Comment by TomWarren** [comment]
The phrase "with (or by) many convincing proofs" was added. 
\v 3 After his suffering, he presented himself alive to them with many convincing proofs. For forty days he appeared to them, and he spoke about the kingdom of God.
