### ISSUE TITLE
Χριστοῦ is rendered as Anointed One in ACT 4:26

### ISSUE THREAD

**Issue by beniza** [unfoldingWord/ulb-en#2]
Is there a specific reason why we choose to render it this way instead of "CHRIST"? I thought ULB's objective is to be as much as literal. In many Indian Bibles, the term is rendered as CHRIST and the teams were confused, if they should change it to **Anointed One**, as per the rendering of ULB.

**Comment by TomWarren** [comment]
This was changed in the ULB to "Christ." Anointed is the translation of "Messiah" in Psalm 2:2, and it a synonym of Christ. Christ (in Greek) means "Anointed One," as does "Messiah" in Hebrews. Christ (christos in Greek) occurs 30 times in Acts and in every other case, it was rendered, "Christ." And so it was changed here to "Christ" and a note was added to the Translation Notes.
